version: '2'
services:
  spark_job:
    build:
      context: ./spark_job
    command: bin/spark-submit --packages org.mongodb.spark:mongo-spark-connector_2.11:2.4.1,\org.apache.spark:spark-streaming-kafka-0-8_2.11:2.0.2 spark_job.py
    environment:
      MONGODB_URI: mongodb://${MONGODB_CREDENTIALS}@${MONGODB_NODES}/${MONGODB_DATABASE}.{$MONGODB_COLLECTION}?${MONGODB_ARGS}
      SPARK_STREAMING_DELAY: 20
      SPARK_LOGS: spark_job.log
      KAFKA_TOPIC: raw_vacancies
      KAFKA_BROKERS: kafka-1:19092 kafka-2:29092
      PYTHONUNBUFFERED: 1

  connector-1:
    build:
      context: ./connector
    command: python3 connector.py
    environment:
      REQUESTS_TIMEOUT: 60
      REQUESTS_URL_PATTERN: https://api.hh.ru/vacancies/%s
      KAFKA_TOPIC: raw_vacancies
      KAFKA_BROKERS: kafka-1:19092 kafka-2:29092
      PYTHONUNBUFFERED: 1
      START_DOWNLOADING_AFTER: 30
      CONNECTOR_LOGS: connector.log
      START_ID: 0
      STOP_ID: 500000
      STEP: 50

